# Generated by Django 5.1.7 on 2025-04-15 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='log_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged'),
        ),
    ]
